# Generated by Django 4.2.11 on 2024-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="csv",
            field=models.JSONField(),
        ),
    ]
