# Generated by Django 4.2.11 on 2024-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metrics",
            name="fuel_level",
        ),
        migrations.RemoveField(
            model_name="metrics",
            name="speed",
        ),
        migrations.AddField(
            model_name="metrics",
            name="data",
            field=models.CharField(default="*", max_length=1000),
        ),
    ]
