# Generated by Django 4.2.11 on 2024-11-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_manager", "0002_remove_metrics_fuel_level_remove_metrics_speed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metrics",
            name="data",
            field=models.TextField(),
        ),
    ]
